### ISSUE TITLE
我们学校的课程代码应该怎么输入

### ISSUE THREAD

**Issue by RuioWolf** [imlinhanchao/zfxk2#3]
![image](https://cloud.githubusercontent.com/assets/15277799/24232777/520e9e5e-0fc8-11e7-9f7a-b3506a84374f.png)
比如这样，有些课程一样时间不同的最多最后的那个10变成11，那么课程代码应该怎么输入？
是`(2016-2017-2)-01P686432-100624-10`吗

**Comment by imlinhanchao** [comment]
以选课网页上的课号为准。

**Comment by RuioWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/15277799/24240086/5e0364d8-0feb-11e7-8556-c51218081a6f.png)

选课前网页中的课号是这样的，课程相同但是上课时间是不一样的，还是说以1楼中选课后的课号（可以看网页源码查到）为准？

**Comment by imlinhanchao** [comment]
你不是深圳信息职业技术学院的吧？要适配得修改哦~

**Comment by RuioWolf** [comment]
我自己修改了一下非核心部分，但是具体post什么的我是完全不懂的。。你可以看一下我的仓库，里面有fork了一份你的代码，第一次在github上修改东西，有很多不懂的还请多指教233

**Comment by imlinhanchao** [comment]
你要依照实际chrome抓包为准，我看了你们教务系统的首页，登录就与我们的不一样了。所以首先你要先抓包看实际请求方式，修改Post的内容。

**Comment by RuioWolf** [comment]
可以详细的教教我吗233有些东西我还不是很熟悉，如果可以的话可以在我的主页最底部找到我的联系方式～

**Comment by imlinhanchao** [comment]
我要上班，没有时间去教你，请先Google一下模拟登录的资料。

**Comment by RuioWolf** [comment]
哦哦好的

**Comment by RuioWolf** [comment]
哦对了不知道为什么密码错误他也会提示登陆成功，是我这边学校的问题吗

**Comment by imlinhanchao** [comment]
有可能。
